import * as React from "react";
import Header from "./header"
import Footer from "./footer"
import Head from "next/head";
import { useAuthState } from "react-firebase-hooks/auth";
import { auth } from "../../firebase/clientApp";
export const Layout:React.FC = ({ children }) => {
    const [user] = useAuthState(auth)
    
    if (!user){
        console.log("gaada user");
    } else{
        console.log("hai2");
        console.log(user);
    }

    return(
        <div className="flex flex-col min-h-screen">
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <Header data={user}/>
            <main className="flex flex-col mx-40 my-24">
                {children}
            </main>
            {/* <Footer/> */}
        </div>
    )
}