import type { NextPage } from 'next'
import Head from 'next/head'
import styles from '../styles/Home.module.css'
import {useAuthState} from 'react-firebase-hooks/auth'
import {auth} from '../src/firebase/clientApp'
import { signOut } from 'firebase/auth'
import { useRouter } from 'next/router'
const Home: NextPage = () => {
  const router = useRouter();
  const [user, loading, error] = useAuthState(auth);
  console.log(user?.email);
  
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <h1>HELLOOOOOO</h1>
      <button onClick={() => { signOut(auth).then(()=>{
        router.push('/auth')
        console.log("keluar");
        
      })}}>keluar</button>
    </div>
  )
}

export default Home
